# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anamika Sen
full_name: Anamika Sen
email: anamikasen@umass.edu
email2: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anamika-sen.github.io" # the base hostname & protocol for your site
github_username:  anamika-sen
twitter_username: anamika716
linkedin_username: anamika-sen-35804775
stackoverflow: 
include: ['_pages']
footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
